//
//  AudioItemEventProducer.swift
//  AudioPlayer
//
//  Created by Kevin DELANNOY on 13/03/16.
//  Copyright © 2016 Kevin Delannoy. All rights reserved.
//

import Foundation

// MARK: - AudioItem+KVO

extension AudioItem {
    //swiftlint:disable variable_name
    /// The list of properties that is observed through KVO.
    fileprivate static var ap_KVOProperties: [String] {
        return AudioItemEventProducer.AudioItemEvent.allCases.map{$0.rawValue} //["artist", "title", "album", "trackCount", "trackNumber", "artwork"]
    }
}

// MARK: - PlayerEventProducer

/// An `AudioItemEventProducer` generates event when a property of an `AudioItem` has changed.
class AudioItemEventProducer: NSObject, EventProducerP {
    
    /// An `AudioItemEvent` gets generated by `AudioItemEventProducer` when a property of `AudioItem` changes.
    enum AudioItemEvent: String, EventP, CaseIterable {
        
        case updatedArtist = "artist"
        case updatedTitle = "title"
        case updatedAlbum = "album"
        case updatedTrackCount = "trackCount"
        case updatedTrackNumber = "trackNumber"
        case updatedArtwork = "artwork"
    }

    /// The player to produce events with.
    /// Note that setting it has the same result as calling `stopProducing`.
    var item: AudioItem? {
        willSet {
            stopProducing()
        }
    }

    weak var eventListener: EventListenerP?

    private var listening = false

    
    //MARK: -

    /// Starts listening to the player events.
    func startProducing() {
        guard let item = item, !listening else {
            return
        }

        //Observing AudioItem's property
        AudioItem.ap_KVOProperties.forEach { keyPath in
            item.addObserver(self, forKeyPath: keyPath, options: .new, context: nil)
        }
        listening = true
    }

    /// Stops listening to the player events.
    func stopProducing() {
        guard let item = item, listening else {
            return
        }

        //Unobserving AudioItem's property
        AudioItem.ap_KVOProperties.forEach { keyPath in
            item.removeObserver(self, forKeyPath: keyPath)
        }

        listening = false
    }

    /// This message is sent to the receiver when the value at the specified key path relative to the given object has
    /// changed. The receiver must be registered as an observer for the specified `keyPath` and `object`.
    ///
    /// - Parameters:
    ///   - keyPath: The key path, relative to `object`, to the value that has changed.
    ///   - object: The source object of the key path `keyPath`.
    ///   - change: A dictionary that describes the changes that have been made to the value of the property at the key
    ///         path `keyPath` relative to `object`. Entries are described in Change Dictionary Keys.
    ///   - context: The value that was provided when the receiver was registered to receive key-value observation
    ///         notifications.
    override func observeValue(forKeyPath keyPath: String?,
                               of object: Any?,
                               change: [NSKeyValueChangeKey: Any]?,
                               context: UnsafeMutableRawPointer?) {
        
        if let event = keyPath.flatMap({
            AudioItemEvent(rawValue: $0) }) {
            
            eventListener?.onEvent(event, generetedBy: self)
        }
    }
    
    deinit {
        stopProducing()
    }
}
