//
//  EventProducerP.swift
//  AudioPlayer
//
//  Created by Kevin DELANNOY on 08/03/16.
//  Copyright © 2016 Kevin Delannoy. All rights reserved.
//

import Foundation

protocol EventP {}

/// An `EventListenerP` listens to events generated by a `EventProducerP`.
protocol EventListenerP: class {
    
    /// Called when an event occurs.
    func onEvent(_ event: EventP,
                 generetedBy eventProducer: EventProducerP)
}

/// An `EventProducerP` serves the purpose of producing events over time.
protocol EventProducerP: class {
    
    var eventListener: EventListenerP? { get set }

    /// Tells the producer to start producing events.
    func startProducing()

    /// Tells the producer to stop producing events.
    func stopProducing()
}
